name: validated
version: 1.0.3
description: The ultimate string validator for dart and flutter with over 40+ validators
homepage: https://github.com/pacifio/validated
environment:
  sdk: ">=2.12.0<3.0.0"
dev_dependencies:
  test: ^1.17.10
